on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://gitlab.com/fdroid/fdroidclient"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
    - name: Create PR to branch
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: 'edt'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: luandro@digital-democracy.org
        DRY_RUN: true
